### ISSUE TITLE
UI - Runs relating to a thread are listed with the most recent one in the top. `Triggered On` heading needs to be altered.

### ISSUE THREAD

**Issue by sangee2004** [obot-platform/obot#105]
**Steps to reproduce the problem:**
1. Create a workflow with following file ( otto create -f  <filename>)
```
name: TestWorkflow
tools:
  - "github.com/gptscript-ai/tools/apis/google/sheets/write"
steps:
   - step: open an existing google sheet with name mypay2023
   - step: Add a new column - Net Tax 
   - step: Fill in the values of this column as difference between "Gross Pay" and "Net Pay" as a numeric value
   - step: Append a new row with values for Gross Pay, Net Pay and Net Tax to be total of all rows from the pervious rows  
```
File used for step1 -
[mypay2023.xlsx](https://github.com/user-attachments/files/17216893/mypay2023.xlsx)

2. Invoke this workflow - `otto invoke  <workflow id>`
Once  done , notice that the most recent step is presented in the top which is confusing.

<img width="1126" alt="Screenshot 2024-10-01 at 3 08 13 PM" src="https://github.com/user-attachments/assets/2fb471cf-cea6-431f-9da6-f40d8e175314">

`Triggered On` heading needs to be altered to reflect the fact that the time shown is not a timestamp but indicates how much time before this run was done.
