### ISSUE TITLE
Google Sheet Tool -Able to work with deleted sheets.

### ISSUE THREAD

**Issue by sangee2004** [obot-platform/obot#108]
**Steps to reproduce the problem:**
1. Create a workflow with following file ( `otto create -f  <filename>`)
```
name: TestWorkflow
tools:
  - "github.com/gptscript-ai/tools/apis/google/sheets/write"
steps:
   - step: open an existing google sheet with name mypay
   - step: Add a new row with values for Gross Pay, Net Pay and Net Tax to be the total of corresponding column values from all the pervious rows   
```   
2. Have the following files created in sheets as `mypay` - (https://github.com/user-attachments/files/17216893/mypay2023.xlsx)
3. Delete the sheet (using google sheet ui)
4. Run the workflow using (`otto invoke <workflow id>`)

Notice that changes are actually made to the deleted `mypay` sheet which can be found in `Trash` folder in google drive.

**Expected Behavior:**
We should not be making changes to the deleted sheets and report an error stating that the sheet has been deleted/does not exists. 
Using google drive UI , we are not allowed to work on deleted sheets unless they are restored.
