### ISSUE TITLE
Agent chat gets stuck and further getting context cancelled response

### ISSUE THREAD

**Issue by himanshusharma89** [obot-platform/obot#1092]
Upon adding a custom Tool and adding it to a new Agent, the Agents get stuck as soon as you ask the agent to do something related to that tool

Later if you send another msg and refresh, you can then inspect the previous stuck msg (new msg no where to be seen) with the "context cancelled" reponse

![image](https://github.com/user-attachments/assets/c167ced4-24da-4e9b-a10f-1ce50b69d435)

Upon inspecting the response, I can see expected response in the sub call of my Tool. However, it seems to get stuck while getting the full response

[calls (1).json](https://github.com/user-attachments/files/18289044/calls.1.json)

Note: The tool.gpt works using gptscript cli, however the same isn't working on Obot

```yaml
Name: MovieRecommender
Chat: true
Description: Fetches top-rated movies from TMDb based on a specified genre or keyword.
Param: query: The movie genre or keyword to fetch.

You are tasked with fetching and formatting movie data. Follow these steps:

1. Use the provided `query` parameter to query the TMDb API and fetch movie data.
2. Filter the results:
   - Include titles, ratings, and release years.
   - Select a maximum of 10 movies, sorted by rating in descending order.
3. Format the results into a markdown list:
   - Use bullet points for each movie.
   - Include the title, rating, and release year.
   - Optionally, add trivia or a short comment for user engagement.
4. Return the formatted markdown list for display.

#!/usr/bin/env npm --silent --prefix ${GPTSCRIPT_TOOL_DIR} run tool -- recommend-movie
```
