### ISSUE TITLE
Google Sheets Tool - Provide a way to create cells with formula.

### ISSUE THREAD

**Issue by sangee2004** [obot-platform/obot#116]
**Steps to reproduce the problem:**
1. Create a workflow with following file ( otto create -f  <filename>)

```
name: TestWorkflow
tools:
  - "github.com/gptscript-ai/tools/apis/google/sheets/write"
steps:
   - step: open an existing google sheet with name mypay
   - step: Add a new row with values for Gross Pay and Net Pay to be the total of corresponding column values from all the pervious rows   
```

File used for step1 - [mypay.xlsx](https://github.com/user-attachments/files/17237182/mypay.xlsx) in google sheets.

2. Invoke this workflow

```
otto invoke w1t66vt
 
> open an existing google sheet with name mypay
> Running tool (listSpreadsheets): {}
> Running tool (readSpreadsheet): {"spreadsheet_id":"1fzUmNOf9zkYfBDBm1ieke0lInRyW9f77NAnkuRo9jjc"}
 
I have opened the Google Sheet named "mypay". Here is a summary of the data:

- **Columns**: 
  - File Path
  - Pay Period
  - Gross Pay
  - Net Pay

- **Sample Data**:
  - **Row 2**: 
    - File Path: `paystubs/2023/paystub-XYZ-20230101-20230115-foo bar.pdf`
    - Pay Period: `01/12/2023 - 01/15/2023`
    - Gross Pay: `$1,666.67`
    - Net Pay: `$666.67`
  - **Row 3**: 
    - File Path: `paystubs/2023/paystub-XYZ-20230116-20230131-foo bar.pdf`
    - Pay Period: `01/16/2023 - 01/31/2023`
    - Gross Pay: `$1,333.33`
    - Net Pay: `$333.33`

The sheet contains paystub information from January 2023 to September 2024. If you need more specific details or further actions, please let me know! 
 
> Add a new row with values for Gross Pay and Net Pay to be the total of corresponding column values from all the pervious rows
> Running tool (appendCellsToSpreadsheet): {"spreadsheet_id":"1fzUmNOf9zkYfBDBm1ieke0lInRyW9f77NAnkuRo9jjc","data":"\"Total\",\"\",\"$66,250.00\",\"$26,250.00\""}
 
I have added a new row to the Google Sheet "mypay" with the total values for Gross Pay and Net Pay:

- **Gross Pay Total**: $66,250.00
- **Net Pay Total**: $26,250.00

If you need any more assistance, feel free to ask! 
 
```

The new total row that gets created has invalid values and is not the sum of all previous Gross Pay and Net Pay entries.

**Expected Behavior:**
We should be able to create cells with formula so that the values can be computed by google sheet instead of having to rely on the LLM to do the calculation which always ends up being incorrect.
