### ISSUE TITLE
[question] how to add new auth provider?

### ISSUE THREAD

**Issue by tuananh** [obot-platform/obot#1691]
i understand that i will need to fork the tools repo and add one there.

however, i'm not sure what other step do i need in order for it to show up in auth provider web admin.

any pointers are much appreciated

**Comment by tybalex** [comment]
hi @tuananh , to show your new auth provider, you would need to reference it in `index.yaml`:

for example:
```
authProviders:
  github-auth-provider:
    reference: ./github-auth-provider
  google-auth-provider:
    reference: ./google-auth-provider
  your-new-auth-provider:
    reference: ./<new-auth-provider-implementation-dir>
```
